swagger-api:
  version: "1.0"

spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/userbook
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info